version: '3'

services:
  database:
    container_name: agendae_db
    image: postgres
    restart: on-failure
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: agendae
    volumes:
      - agendae_db:/var/lib/postgresql

volumes:
  agendae_db:
