version: '3'

services:
  database:
    container_name: agendae_db
    image: postgres:14.5
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: agendae
    volumes:
      - agendae_db:/var/lib/postgresql

volumes:
  agendae_db:
